import { Pool } from 'pg';
import crypto from 'node:crypto';

export const LIVE_MUST_BE_OFF=true;
const DATABASE_URL=process.env.DATABASE_URL||process.env.AUREVIX_DATABASE_URL;
export function databaseConfigured(){return Boolean(DATABASE_URL);}
export function requireDatabase(){if(!DATABASE_URL)throw new Error('AUTHORITATIVE_DATABASE_URL_NOT_CONFIGURED');}
const pool=DATABASE_URL?new Pool({connectionString:DATABASE_URL,ssl:{rejectUnauthorized:true},max:4,idleTimeoutMillis:10000,connectionTimeoutMillis:10000}):null;
export async function closeDatabase(){await pool?.end();}
export async function initDurableState(){requireDatabase();await pool.query(`CREATE TABLE IF NOT EXISTS aurevix_runtime_state(key TEXT PRIMARY KEY,value JSONB NOT NULL,version BIGINT NOT NULL DEFAULT 0,updated_at TIMESTAMPTZ NOT NULL DEFAULT now());CREATE TABLE IF NOT EXISTS aurevix_lease(key TEXT PRIMARY KEY,owner_id TEXT NOT NULL,expires_at TIMESTAMPTZ NOT NULL,fence BIGINT NOT NULL,updated_at TIMESTAMPTZ NOT NULL DEFAULT now());CREATE TABLE IF NOT EXISTS aurevix_idempotency(key TEXT PRIMARY KEY,status TEXT NOT NULL,payload JSONB NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now());CREATE TABLE IF NOT EXISTS aurevix_journal(id BIGSERIAL PRIMARY KEY,event_type TEXT NOT NULL,payload JSONB NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now());CREATE TABLE IF NOT EXISTS aurevix_backup(id UUID PRIMARY KEY,sha256 TEXT NOT NULL,snapshot JSONB NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now());`);return true;}
export async function acquireLease({key='EXECUTION_AUTHORITY',ownerId=crypto.randomUUID(),ttlMs=90000}={}){requireDatabase();const c=await pool.connect();try{await c.query('BEGIN');const now=new Date(),exp=new Date(now.getTime()+ttlMs);const current=await c.query('SELECT owner_id,expires_at,fence FROM aurevix_lease WHERE key=$1 FOR UPDATE',[key]);if(current.rowCount&&new Date(current.rows[0].expires_at)>now&&current.rows[0].owner_id!==ownerId){await c.query('ROLLBACK');return {acquired:false,ownerId:current.rows[0].owner_id,expiresAt:current.rows[0].expires_at,fence:Number(current.rows[0].fence)};}const fence=(current.rowCount?Number(current.rows[0].fence):0)+1;await c.query(`INSERT INTO aurevix_lease(key,owner_id,expires_at,fence) VALUES($1,$2,$3,$4) ON CONFLICT(key) DO UPDATE SET owner_id=EXCLUDED.owner_id,expires_at=EXCLUDED.expires_at,fence=EXCLUDED.fence,updated_at=now()`,[key,ownerId,exp,fence]);await c.query('COMMIT');return {acquired:true,ownerId,expiresAt:exp.toISOString(),fence};}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
export async function renewLease({key='EXECUTION_AUTHORITY',ownerId,fence,ttlMs=90000}={}){requireDatabase();const exp=new Date(Date.now()+ttlMs);const r=await pool.query(`UPDATE aurevix_lease SET expires_at=$1,updated_at=now() WHERE key=$2 AND owner_id=$3 AND fence=$4 AND expires_at>now() RETURNING fence,expires_at`,[exp,key,ownerId,fence]);return {renewed:r.rowCount===1,fence:r.rows[0]?.fence??null,expiresAt:r.rows[0]?.expires_at??null};}
export async function assertLease({key='EXECUTION_AUTHORITY',ownerId,fence}={}){requireDatabase();const r=await pool.query('SELECT owner_id,fence,expires_at FROM aurevix_lease WHERE key=$1',[key]);const ok=r.rowCount===1&&r.rows[0].owner_id===ownerId&&Number(r.rows[0].fence)===Number(fence)&&new Date(r.rows[0].expires_at)>new Date();return {ok,ownerId:r.rows[0]?.owner_id??null,fence:Number(r.rows[0]?.fence??0),expiresAt:r.rows[0]?.expires_at??null};}
export async function fencedWrite({key,ownerId,fence,payload}){const gate=await assertLease({key,ownerId,fence});if(!gate.ok)throw new Error('STALE_FENCE_EXECUTION_BLOCK');await pool.query(`INSERT INTO aurevix_runtime_state(key,value,version) VALUES($1,$2,$3) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value,version=EXCLUDED.version,updated_at=now()`,[key,payload,fence]);return {written:true,fence};}
export async function putState(key,value,version=0){requireDatabase();await pool.query(`INSERT INTO aurevix_runtime_state(key,value,version) VALUES($1,$2,$3) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value,version=EXCLUDED.version,updated_at=now()`,[key,value,version]);}
export async function getState(key){requireDatabase();const r=await pool.query('SELECT key,value,version,updated_at FROM aurevix_runtime_state WHERE key=$1',[key]);return r.rows[0]??null;}
export async function journal(eventType,payload){requireDatabase();await pool.query('INSERT INTO aurevix_journal(event_type,payload) VALUES($1,$2)',[eventType,payload]);}
export async function idempotencyGet(key){requireDatabase();const r=await pool.query('SELECT key,status,payload FROM aurevix_idempotency WHERE key=$1',[key]);return r.rows[0]??null;}
export async function idempotencyPut(key,status,payload){requireDatabase();await pool.query('INSERT INTO aurevix_idempotency(key,status,payload) VALUES($1,$2,$3) ON CONFLICT(key) DO NOTHING',[key,status,payload]);}
function canonicalSnapshot(tables){return JSON.stringify({runtime:tables.runtime,lease:tables.lease,idempotency:tables.idempotency,journal:tables.journal});}
export async function backupDurableState(){requireDatabase();const c=await pool.connect();try{await c.query('BEGIN');const tables={runtime:(await c.query('SELECT * FROM aurevix_runtime_state ORDER BY key')).rows,lease:(await c.query('SELECT * FROM aurevix_lease ORDER BY key')).rows,idempotency:(await c.query('SELECT * FROM aurevix_idempotency ORDER BY key')).rows,journal:(await c.query('SELECT * FROM aurevix_journal ORDER BY id')).rows};const snapshot=canonicalSnapshot(tables);const sha256=crypto.createHash('sha256').update(snapshot).digest('hex');const id=crypto.randomUUID();await c.query('INSERT INTO aurevix_backup(id,sha256,snapshot) VALUES($1,$2,$3::jsonb)',[id,sha256,snapshot]);await c.query('COMMIT');return {id,sha256};}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
export async function restoreDurableState(backupId){requireDatabase();const c=await pool.connect();try{await c.query('BEGIN');const r=await c.query('SELECT sha256,snapshot FROM aurevix_backup WHERE id=$1',[backupId]);if(!r.rowCount)throw new Error('BACKUP_NOT_FOUND');const snapshot=r.rows[0].snapshot;const canonical=canonicalSnapshot(snapshot);const sha256=crypto.createHash('sha256').update(canonical).digest('hex');if(sha256!==r.rows[0].sha256)throw new Error('BACKUP_CHECKSUM_MISMATCH');await c.query('TRUNCATE aurevix_runtime_state,aurevix_lease,aurevix_idempotency,aurevix_journal RESTART IDENTITY');for(const row of snapshot.runtime)await c.query(`INSERT INTO aurevix_runtime_state(key,value,version,updated_at) VALUES($1,$2,$3,$4)`,[row.key,row.value,row.version,row.updated_at]);for(const row of snapshot.lease)await c.query(`INSERT INTO aurevix_lease(key,owner_id,expires_at,fence,updated_at) VALUES($1,$2,$3,$4,$5)`,[row.key,row.owner_id,row.expires_at,row.fence,row.updated_at]);for(const row of snapshot.idempotency)await c.query(`INSERT INTO aurevix_idempotency(key,status,payload,created_at) VALUES($1,$2,$3,$4)`,[row.key,row.status,row.payload,row.created_at]);for(const row of snapshot.journal)await c.query(`INSERT INTO aurevix_journal(id,event_type,payload,created_at) VALUES($1,$2,$3,$4)`,[row.id,row.event_type,row.payload,row.created_at]);await c.query('COMMIT');return {restored:true,sha256};}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
export async function backupChecksum(backupId){requireDatabase();const r=await pool.query('SELECT sha256,snapshot FROM aurevix_backup WHERE id=$1',[backupId]);if(!r.rowCount)throw new Error('BACKUP_NOT_FOUND');const actual=crypto.createHash('sha256').update(canonicalSnapshot(r.rows[0].snapshot)).digest('hex');return {match:actual===r.rows[0].sha256,expected:r.rows[0].sha256,actual};}