import { evaluateRisk, evaluateKillSwitch } from './safety-engine.mjs';

export const AUREVIX_TIMEFRAMES = Object.freeze(['4H','1H','15M','5M']);
const MIN_BARS = 60;
const clamp=(x,a=0,b=100)=>Math.max(a,Math.min(b,x));
const avg=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0;
function ema(values,p){const k=2/(p+1);let e=values[0]??0;return values.map((v,i)=>i?e=v*k+e*(1-k):e);}
function rsi(values,p=14){const out=Array(values.length).fill(50);let gain=0,loss=0;for(let i=1;i<values.length;i++){const d=values[i]-values[i-1];gain+=Math.max(d,0);loss+=Math.max(-d,0);if(i>=p){if(i>p){const old=values[i-p]-values[i-p-1];gain-=Math.max(old,0);loss-=Math.max(-old,0);}out[i]=loss?100-100/(1+gain/loss):100;}}return out;}
function atr(bars,p=14){const tr=bars.map((b,i)=>i?Math.max(b.high-b.low,Math.abs(b.high-bars[i-1].close),Math.abs(b.low-bars[i-1].close)):b.high-b.low);const out=Array(bars.length).fill(null);let s=0;for(let i=0;i<tr.length;i++){s+=tr[i];if(i>=p)s-=tr[i-p];if(i>=p-1)out[i]=s/p;}return out;}
function macd(values){const e12=ema(values,12),e26=ema(values,26),line=values.map((_,i)=>e12[i]-e26[i]),sig=ema(line,9);return {line,signal:sig,hist:line.map((x,i)=>x-sig[i])};}
function vwap(bars){let pv=0,v=0;return bars.map(b=>{const tp=(b.high+b.low+b.close)/3;pv+=tp*b.volume;v+=b.volume;return v?pv/v:tp;});}
function structure(bars,i,look=20){const s=bars.slice(Math.max(0,i-look),i);return s.length?{high:Math.max(...s.map(x=>x.high)),low:Math.min(...s.map(x=>x.low))}:{high:null,low:null};}
function normalizeBars(rows){return rows.map(x=>({time:Number(x.time),open:Number(x.open),high:Number(x.high),low:Number(x.low),close:Number(x.close),volume:Number(x.volume??x.vol??0)})).filter(b=>[b.time,b.open,b.high,b.low,b.close,b.volume].every(Number.isFinite)).sort((a,b)=>a.time-b.time);}
function tfAnalysis(bars){if(bars.length<MIN_BARS)return null;const c=bars.map(x=>x.close),i=c.length-1,e20=ema(c,20)[i],e50=ema(c,50)[i],r=rsi(c)[i],a=atr(bars)[i]??0,m=macd(c),v=vwap(bars)[i],st=structure(bars,i),price=c[i];const trend=e20>e50?1:e20<e50?-1:0,momentum=m.hist[i]>0?1:m.hist[i]<0?-1:0,volumeBase=avg(bars.slice(-20).map(x=>x.volume)),volumeScore=volumeBase>0?clamp(bars[i].volume/volumeBase*50):50,breakout=st.high!==null&&price>st.high?1:st.low!==null&&price<st.low?-1:0,rejection=(bars[i].close>bars[i].open&&bars[i].low<=e20&&bars[i].close>e20)?1:(bars[i].close<bars[i].open&&bars[i].high>=e20&&bars[i].close<e20)?-1:0,vwapBias=price>v?1:price<v?-1:0,rsiBias=r>=55?1:r<=45?-1:0,directional=trend+momentum+breakout+rejection+vwapBias+rsiBias,bias=directional>=2?1:directional<=-2?-1:0,strength=clamp(Math.abs(price-e50)/(a||price)*20);return {time:bars[i].time,price,ema20:e20,ema50:e50,rsi:r,atr:a,macd:m.hist[i],vwap:v,support:st.low,resistance:st.high,trend,momentum,volumeScore,breakout,rejection,vwapBias,rsiBias,bias,strength};}
function regime(a){if(!a)return 'UNKNOWN';const p=a.price||1,atrPct=Math.abs(a.atr/p)*100;if(atrPct>2.5)return 'EXTREME';if(atrPct>1.2)return 'HIGH_VOLATILITY';if(Math.abs(a.ema20-a.ema50)/p<0.002)return 'RANGE';return 'TRENDING';}
export function evaluateSignalEngine({tf4h,tf1h,tf15m,tf5m,accountEquity=15,dayPnl=0,weekPnl=0,monthPnl=0,drawdown=0,openPositions=0,openRisk=0,consecutiveLosses=0,dailyTrades=0,now=Date.now()}){
 const b4=normalizeBars(tf4h),b1=normalizeBars(tf1h),b15=normalizeBars(tf15m),b5=normalizeBars(tf5m);for(const b of [b4,b1,b15,b5])if(b.length<MIN_BARS)throw new Error('INSUFFICIENT_CLOSED_BARS');
 const final5=b5.at(-1);const analyses={};for(const [k,b] of [['4H',b4],['1H',b1],['15M',b15],['5M',b5]])analyses[k]=tfAnalysis(b.filter(x=>x.time<=final5.time));
 const [a4,a1,a15,a5]=[analyses['4H'],analyses['1H'],analyses['15M'],analyses['5M']];
 const directions=[a4.bias,a1.bias,a15.bias,a5.bias],conflict=(a4.bias&&a1.bias&&a4.bias!==a1.bias)||(a1.bias&&a15.bias&&a1.bias!==a15.bias)||(a15.bias&&a5.bias&&a15.bias!==a5.bias);const aligned=directions.filter(x=>x!==0&&x===a4.bias).length,alignmentPct=Math.round(aligned/4*100),overallBias=a4.bias||0;
 const setupQuality=clamp(alignmentPct*.35+Math.abs(a15.strength)*.25+Math.abs(a15.volumeScore-50)*.35+Math.abs(a15.breakout)*10+Math.abs(a15.rejection)*10);
 const entryConfirmation=a5.bias===overallBias&&a5.bias!==0;let fusion=overallBias?(alignmentPct*.35+setupQuality*.35+(entryConfirmation?20:0)+(Math.abs(a5.momentum)?10:0)):0;if(conflict)fusion=Math.min(fusion,49);const confidence=Math.round(clamp(fusion));
 const regimes=[a4,a1,a15,a5].map(regime);const marketRegime=regimes.includes('EXTREME')?'EXTREME':(['TRENDING','RANGE','HIGH_VOLATILITY'].find(r=>regimes.filter(x=>x===r).length>=2)||regimes[3]||'UNKNOWN');
 const finalSignal=!conflict&&entryConfirmation&&confidence>=65&&marketRegime!=='EXTREME'?(overallBias===1?'LONG':'SHORT'):'WAIT';
 const rr=2;const risk=evaluateRisk({dailyLossPct:dayPnl,weeklyLossPct:weekPnl,monthlyLossPct:monthPnl,drawdownPct:drawdown,consecutiveLosses,dailyTrades,openPositions,portfolioRiskPct:openRisk,leverage:10,rr,nowMs:now});
 const kill=evaluateKillSwitch({dailyHardLoss:dayPnl<=-1.5,weeklyLimit:weekPnl<=-4,monthlyLimit:monthPnl<=-8,maxDrawdown:drawdown>=10,consecutiveLosses:consecutiveLosses>=3,extremeVolatility:marketRegime==='EXTREME',apiFailure:false,dataFailure:false,reconciliationFailure:false,emergencyStop:false});
 const positionRiskPct=Math.max(0,Number(risk.allowedRiskPct??0));const stopDistancePct=Math.max(0.005,Math.min(0.03,(a5.atr/Math.max(a5.price,1))*2));const positionNotional=accountEquity*(positionRiskPct/100)/stopDistancePct;const dynamicLeverage=Math.max(7,Math.min(18,Math.round((positionNotional/Math.max(accountEquity,1))*2)));
 const executionAllowed=finalSignal!=='WAIT'&&risk.pass===true&&kill.pass===true&&rr>=1.8&&dynamicLeverage>=7&&dynamicLeverage<=18;
 return {closedCandleTime:final5.time,overallBias:overallBias===1?'LONG':overallBias===-1?'SHORT':'NEUTRAL',trendAlignmentPct:alignmentPct,setupQuality:Math.round(setupQuality),timeframeConflict:Boolean(conflict),finalSignal,confidence,marketRegime,rr,positionRiskPct,positionNotional,dynamicLeverage,leverage:dynamicLeverage,executionAllowed,executionGate:{allowed:executionAllowed,result:executionAllowed?'PAPER_AUTHORIZED':'EXECUTION_BLOCKED'},indicators:analyses,risk,kill,technicalInputs:['EMA','RSI','ATR','MACD','Volume','VWAP','Support/Resistance','Market Structure','Breakout','Rejection','Momentum','Volatility'],pipeline:['4H Market Bias','1H Trend Confirmation','15M Trade Setup','5M Final Entry Confirmation','Signal Fusion','Confidence','Market Regime','Risk Engine','Position Size','Dynamic Leverage','R:R','Execution Gate']};
}
export function paperIntent(signal){if(signal.executionAllowed!==true||signal.finalSignal==='WAIT')return {state:'BLOCKED',reason:'SIGNAL_OR_RISK_GATE',ordersSent:0,positionsModified:0};return {state:'PAPER_INTENT',side:signal.finalSignal,clientId:`paper-${signal.closedCandleTime}-${signal.finalSignal}`,ordersSent:0,positionsModified:0};}
export { normalizeBars };