import { SAFETY_LIMITS, evaluateRisk, evaluateKillSwitch } from './safety-engine.mjs';

export const AUREVIX_TIMEFRAMES = Object.freeze(['4H','1H','15M','5M']);
const MIN_BARS = 60;
const clamp=(x,a=0,b=100)=>Math.max(a,Math.min(b,x));
const avg=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0;
function ema(values,p){const k=2/(p+1);let e=values[0]??0;return values.map((v,i)=>i?e=v*k+e*(1-k):e);}
function rsi(values,p=14){const out=Array(values.length).fill(50);let gain=0,loss=0;for(let i=1;i<values.length;i++){const d=values[i]-values[i-1];gain+=Math.max(d,0);loss+=Math.max(-d,0);if(i>=p){if(i>p){const old=values[i-p]-values[i-p-1];gain-=Math.max(old,0);loss-=Math.max(-old,0);}const rs=loss?gain/loss:100;out[i]=100-100/(1+rs);}}return out;}
function atr(bars,p=14){const tr=bars.map((b,i)=>i?Math.max(b.high-b.low,Math.abs(b.high-bars[i-1].close),Math.abs(b.low-bars[i-1].close)):b.high-b.low);const out=Array(bars.length).fill(null);let s=0;for(let i=0;i<tr.length;i++){s+=tr[i];if(i>=p)s-=tr[i-p];if(i>=p-1)out[i]=s/p;}return out;}
function macd(values){const e12=ema(values,12),e26=ema(values,26),line=values.map((_,i)=>e12[i]-e26[i]);const sig=ema(line,9);return {line,signal:sig,hist:line.map((x,i)=>x-sig[i])};}
function vwap(bars){let pv=0,v=0;return bars.map(b=>{const tp=(b.high+b.low+b.close)/3;pv+=tp*b.volume;v+=b.volume;return v?pv/v:tp;});}
function structure(bars,i,look=20){const s=bars.slice(Math.max(0,i-look),i);if(s.length<5)return {high:null,low:null};return {high:Math.max(...s.map(x=>x.high)),low:Math.min(...s.map(x=>x.low))};}
function normalizeBars(rows){return rows.map(x=>({time:Number(x.time),open:Number(x.open),high:Number(x.high),low:Number(x.low),close:Number(x.close),volume:Number(x.volume??x.vol??0)})).filter(b=>[b.time,b.open,b.high,b.low,b.close,b.volume].every(Number.isFinite)).sort((a,b)=>a.time-b.time);}
function latestAt(bars,t){let lo=0,hi=bars.length-1,best=-1;while(lo<=hi){const m=(lo+hi)>>1;if(bars[m].time<=t){best=m;lo=m+1;}else hi=m-1;}return best>=0?bars[best]:null;}
function tfAnalysis(bars){if(bars.length<MIN_BARS)return null;const c=bars.map(x=>x.close),i=c.length-1,e20=ema(c,20)[i],e50=ema(c,50)[i],r=rsi(c)[i],a=atr(bars)[i]??0,m=macd(c),v=vwap(bars)[i],st=structure(bars,i),price=c[i];const trend=e20>e50?1:e20<e50?-1:0;const momentum=m.hist[i]>0?1:m.hist[i]<0?-1:0;const volumeBase=avg(bars.slice(-20).map(x=>x.volume));const volumeScore=volumeBase>0?clamp(bars[i].volume/volumeBase*50):50;const breakout=st.high!==null&&price>st.high?1:st.low!==null&&price<st.low?-1:0;const rejection=(bars[i].close>bars[i].open&&bars[i].low<=e20&&bars[i].close>e20)?1:(bars[i].close<bars[i].open&&bars[i].high>=e20&&bars[i].close<e20)?-1:0;const vwapBias=price>v?1:price<v?-1:0;const rsiBias=r>=55?1:r<=45?-1:0;const strength=clamp(Math.abs(price-e50)/(a||price)*20);const directional=trend+momentum+breakout+rejection+vwapBias+rsiBias;const bias=directional>=2?1:directional<=-2?-1:0;return {time:bars[i].time,price,ema20:e20,ema50:e50,rsi:r,atr:a,macd:m.hist[i],vwap:v,support:st.low,resistance:st.high,trend,momentum,volumeScore,breakout,rejection,vwapBias,rsiBias,bias,strength};}
function regime(a){if(!a)return 'UNKNOWN';const atrPct=a.price?Math.abs(a.atr/a.price)*100:0;if(atrPct>2.5)return 'EXTREME';if(atrPct>1.2)return 'HIGH_VOLATILITY';if(Math.abs(a.ema20-a.ema50)/a.price<0.002)return 'RANGE';return 'TRENDING';}
export function evaluateSignalEngine({tf4h,tf1h,tf15m,tf5m,accountEquity=15,dayPnl=0,weekPnl=0,monthPnl=0,drawdown=0,openPositions=0,openRisk=0,consecutiveLosses=0,now=Date.now()}){
 const b4=normalizeBars(tf4h),b1=normalizeBars(tf1h),b15=normalizeBars(tf15m),b5=normalizeBars(tf5m);for(const b of [b4,b1,b15,b5])if(b.length<MIN_BARS)throw new Error('INSUFFICIENT_CLOSED_BARS');
 const final5=b5[b5.length-1];const analyses={};for(const [k,b] of [['4H',b4],['1H',b1],['15M',b15],['5M',b5]]){const eligible=b.filter(x=>x.time<=final5.time);analyses[k]=tfAnalysis(eligible);}
 const a4=analyses['4H'],a1=analyses['1H'],a15=analyses['15M'],a5=analyses['5M'];const directions=[a4.bias,a1.bias,a15.bias,a5.bias];const conflict=(a4.bias&&a1.bias&&a4.bias!==a1.bias)||(a1.bias&&a15.bias&&a1.bias!==a15.bias)||(a15.bias&&a5.bias&&a15.bias!==a5.bias);const aligned=directions.filter(x=>x!==0&&x===a4.bias).length;const alignmentPct=Math.round(aligned/4*100);const overallBias=a4.bias||0;const setupQuality=clamp((Math.abs(a15.strength)+Math.abs(a15.volumeScore-50)*0.5+Math.abs(a15.macd/a15.price*10000)+Math.abs(a15.rejection)*15+Math.abs(a15.breakout)*15));const entryConfirmation=a5.bias===overallBias&&a5.bias!==0;let fusion=0;if(overallBias)fusion=(alignmentPct*.35)+setupQuality*.35+(entryConfirmation?20:0)+(Math.abs(a5.momentum) ? 10:0);if(conflict)fusion=Math.min(fusion,49);const confidence=Math.round(clamp(fusion));const marketRegime=[a4,a1,a15,a5].map(regime);const regimeName=marketRegime.includes('EXTREME')?'EXTREME':marketRegime.filter(x=>x!=='UNKNOWN').sort((a,b)=>marketRegime.filter(x=>x===b).length-marketRegime.filter(x=>x===a).length)[0]||'UNKNOWN';const finalSignal=!conflict&&entryConfirmation&&confidence>=65?overallBias===1?'LONG':'SHORT':'WAIT';const riskInput={accountEquity,dayPnl,weekPnl,monthPnl,drawdown,openPositions,openRisk,consecutiveLosses,confidence,rr:2,now};const risk=typeof evaluateRisk==='function'?evaluateRisk(riskInput):{allowed:false,reason:'RISK_ENGINE_UNAVAILABLE'};const kill=typeof evaluateKillSwitch==='function'?evaluateKillSwitch({drawdown,dayPnl,weekPnl,monthPnl}):{allowed:false};const rr=2;const executionAllowed=finalSignal!=='WAIT'&&risk.allowed===true&&kill.allowed===true&&rr>=1.8;
 return {closedCandleTime:final5.time,overallBias:overallBias===1?'LONG':overallBias===-1?'SHORT':'NEUTRAL',trendAlignmentPct:alignmentPct,setupQuality:Math.round(setupQuality),timeframeConflict:Boolean(conflict),finalSignal,confidence,marketRegime:regimeName,rr,executionAllowed,indicators:analyses,risk,kill,technicalInputs:['EMA','RSI','ATR','MACD','Volume','VWAP','Support/Resistance','Market Structure','Breakout','Rejection','Momentum','Volatility'],pipeline:['4H','1H','15M','5M','SIGNAL FUSION','CONFIDENCE','REGIME','RISK','POSITION SIZE','LEVERAGE','R:R','EXECUTION GATE']};
}
export function paperIntent(signal){if(signal.executionAllowed!==true||signal.finalSignal==='WAIT')return {state:'BLOCKED',reason:'SIGNAL_OR_RISK_GATE'};return {state:'PAPER_INTENT',side:signal.finalSignal,clientId:`paper-${signal.closedCandleTime}-${signal.finalSignal}`,ordersSent:0,positionsModified:0};}
export { latestAt, normalizeBars };
