import http from 'node:http';
import crypto from 'node:crypto';
import { initDurableState, acquireLease, renewLease, assertLease, putState, journal, databaseConfigured } from './durable-state.mjs';
import { evaluateSignalEngine } from './signal-engine.mjs';
const REST='https://api.mexc.com';
const PORT=Number(process.env.PORT||10000);const SYMBOL='BTC_USDT';const runtimeId=`runtime-${crypto.randomUUID()}`;const LIVE_ENABLED=String(process.env.AUREVIX_LIVE_TRADING||'DISABLED').toUpperCase()==='ENABLED';
let lease=null,lastCycle=null,lastError=null,lastReadOnly=null,signals=0;
const audit=(event,x={})=>console.log(JSON.stringify({event,service:'aurevix-elite-durable-runtime',runtimeId,at:new Date().toISOString(),liveEnabled:false,ordersSent:0,positionsModified:0,realSlTpModifications:0,canaryStarted:false,...x}));
function gate(){return !LIVE_ENABLED&&databaseConfigured()&&lease?.acquired===true;}
async function publicKline(interval,count=120){const end=Math.floor(Date.now()/1000)-5,start=end-count*interval;const name=interval===14400?'Hour4':interval===3600?'Min60':interval===900?'Min15':'Min5';const r=await fetch(`${REST}/api/v1/contract/kline/${SYMBOL}?interval=${name}&start=${start}&end=${end}`,{headers:{Accept:'application/json'},signal:AbortSignal.timeout(15000)});if(!r.ok)throw new Error(`KLINE_HTTP_${r.status}`);const j=await r.json();if(j?.success===false)throw new Error(`KLINE_API_${j.code??'UNKNOWN'}`);const d=j?.data||j;return Array.from({length:d?.time?.length||0},(_,i)=>({time:Number(d.time[i])*1000,open:Number(d.open[i]),high:Number(d.high[i]),low:Number(d.low[i]),close:Number(d.close[i]),volume:Number(d.vol[i])})).filter(x=>Number.isFinite(x.close)).sort((a,b)=>a.time-b.time).filter(x=>x.time+interval*1000<=Date.now()-5000);}
async function readOnlyAccount(){const key=process.env.MEXC_API_KEY,secret=process.env.MEXC_API_SECRET;if(!key||!secret)return {status:'NOT_CONFIGURED'};const qs=`timestamp=${Date.now()}`;const sig=crypto.createHmac('sha256',secret).update(`${key}${Date.now()}${qs}`).digest('hex');return {status:'CONFIGURED',note:'Authenticated read-only account endpoint is intentionally not called by this durable paper runtime unless credentials are present and endpoint contract is validated'};}
async function cycle(){if(!gate()){lastError='DURABLE_AUTHORITY_OR_LIVE_GATE_BLOCKED';audit('cycle_blocked',{reason:lastError});return;}const [tf4h,tf1h,tf15m,tf5m]=await Promise.all([publicKline(14400,120),publicKline(3600,120),publicKline(900,120),publicKline(300,120)]);const signal=evaluateSignalEngine({tf4h,tf1h,tf15m,tf5m,accountEquity:15,now:Date.now()});signals++;lastCycle=new Date().toISOString();await putState('paper_position',{state:'PAPER_RUNTIME',signal:{finalSignal:signal.finalSignal,confidence:signal.confidence,regime:signal.marketRegime,closedCandleTime:signal.closedCandleTime},ordersSent:0,positionsModified:0,realSlTpModifications:0},lease.fence);await putState('heartbeat',{runtimeId,at:lastCycle,leaseFence:lease.fence,schedulerHealthy:true,liveEnabled:false},lease.fence);await journal('paper_signal',{runtimeId,signal:{finalSignal:signal.finalSignal,confidence:signal.confidence,regime:signal.marketRegime},paperOnly:true});audit('paper_signal_cycle',{result:'PASS',signal:signal.finalSignal,confidence:signal.confidence,regime:signal.marketRegime,executionAllowed:false,reason:'REAL_EXECUTION_DISABLED',ordersSent:0});}
async function start(){if(LIVE_ENABLED)throw new Error('AUREVIX_LIVE_TRADING_MUST_REMAIN_DISABLED');if(!databaseConfigured())throw new Error('AUTHORITATIVE_DATABASE_URL_NOT_CONFIGURED');await initDurableState();lease=await acquireLease({ownerId:runtimeId,ttlMs:90000});if(!lease.acquired)throw new Error('EXECUTION_AUTHORITY_NOT_ACQUIRED');await putState('runtime',{runtimeId,state:'PAPER_RUNTIME',liveEnabled:false,ordersSent:0,positionsModified:0},lease.fence);audit('durable_authority_acquired',{fence:lease.fence,expiresAt:lease.expiresAt});setInterval(async()=>{try{const r=await renewLease({ownerId:runtimeId,fence:lease.fence,ttlMs:90000});if(!r.renewed){lease=null;lastError='AUTHORITY_LOST_NEW_EXECUTION_BLOCK';audit('execution_authority_lost',{reason:lastError});return;}lease={...lease,...r};await putState('heartbeat',{runtimeId,at:new Date().toISOString(),leaseFence:lease.fence,schedulerHealthy:true,liveEnabled:false},lease.fence);}catch(e){lease=null;lastError=e.message;audit('lease_renewal_failed',{reason:lastError});}},15000);await cycle();setInterval(()=>cycle().catch(e=>{lastError=e.message;audit('cycle_error',{error:lastError})}),30000);}
const server=http.createServer((req,res)=>{if(req.url==='/health'||req.url==='/'){const body={service:'aurevix-elite-durable-runtime',runtimeId,readiness:gate()?'READY_HEALTHY':'BLOCKED',liveEnabled:false,ordersSent:0,positionsModified:0,realSlTpModifications:0,canaryStarted:false,lease:lease?{fence:lease.fence,expiresAt:lease.expiresAt}:null,lastCycle,lastReadOnly,lastError,signalCycles:signals};res.writeHead(gate()?200:503,{'content-type':'application/json'});res.end(JSON.stringify(body));return;}res.writeHead(404);res.end('not found');});
server.listen(PORT,()=>audit('http_ready',{port:PORT}));
start().catch(e=>{lastError=e.message;audit('startup_blocked',{reason:lastError});process.exitCode=1;});
