import http from 'node:http';
import crypto from 'node:crypto';
import { spawn } from 'node:child_process';
import { initDurableState, acquireLease, renewLease, assertLease, fencedWrite, journal, databaseConfigured } from './durable-state.mjs';
import { evaluateSignalEngine } from './signal-engine.mjs';
const REST='https://api.mexc.com';
const PORT=Number(process.env.PORT||10000);const SYMBOL='BTC_USDT';const runtimeId=`runtime-${crypto.randomUUID()}`;const LIVE_ENABLED=String(process.env.AUREVIX_LIVE_TRADING||'DISABLED').toUpperCase()==='ENABLED';
let lease=null,lastCycle=null,lastError=null,lastReadOnly=null,signals=0,preflightDone=false;
const audit=(event,x={})=>console.log(JSON.stringify({event,service:'aurevix-elite-durable-runtime',runtimeId,at:new Date().toISOString(),liveEnabled:false,ordersSent:0,positionsModified:0,realSlTpModifications:0,canaryStarted:false,...x}));
function gate(){return !LIVE_ENABLED&&preflightDone&&databaseConfigured()&&lease?.acquired===true;}
async function publicKline(interval,count=120){const end=Math.floor(Date.now()/1000)-5,start=end-count*interval;const name=interval===14400?'Hour4':interval===3600?'Min60':interval===900?'Min15':'Min5';const r=await fetch(`${REST}/api/v1/contract/kline/${SYMBOL}?interval=${name}&start=${start}&end=${end}`,{headers:{Accept:'application/json'},signal:AbortSignal.timeout(15000)});if(!r.ok)throw new Error(`KLINE_HTTP_${r.status}`);const j=await r.json();if(j?.success===false)throw new Error(`KLINE_API_${j.code??'UNKNOWN'}`);const d=j?.data||j;return Array.from({length:d?.time?.length||0},(_,i)=>({time:Number(d.time[i])*1000,open:Number(d.open[i]),high:Number(d.high[i]),low:Number(d.low[i]),close:Number(d.close[i]),volume:Number(d.vol[i])})).filter(x=>Number.isFinite(x.close)).sort((a,b)=>a.time-b.time).filter(x=>x.time+interval*1000<=Date.now()-5000);}
async function cycle(){if(!gate()){lastError='DURABLE_AUTHORITY_OR_LIVE_GATE_BLOCKED';audit('cycle_blocked',{reason:lastError});return;}const authority=await assertLease({ownerId:runtimeId,fence:lease.fence});if(!authority.ok){lease=null;lastError='AUTHORITY_LOST_NEW_EXECUTION_BLOCK';audit('execution_authority_lost',{reason:lastError});return;}const [tf4h,tf1h,tf15m,tf5m]=await Promise.all([publicKline(14400,120),publicKline(3600,120),publicKline(900,120),publicKline(300,120)]);const signal=evaluateSignalEngine({tf4h,tf1h,tf15m,tf5m,accountEquity:15,now:Date.now()});signals++;lastCycle=new Date().toISOString();await fencedWrite({key:'paper_position',ownerId:runtimeId,fence:lease.fence,payload:{state:'PAPER_RUNTIME',runtimeId,signal:{finalSignal:signal.finalSignal,confidence:signal.confidence,regime:signal.marketRegime,closedCandleTime:signal.closedCandleTime},ordersSent:0,positionsModified:0,realSlTpModifications:0}});await fencedWrite({key:'heartbeat',ownerId:runtimeId,fence:lease.fence,payload:{runtimeId,at:lastCycle,leaseFence:lease.fence,schedulerHealthy:true,liveEnabled:false}});await journal('paper_signal',{runtimeId,signal:{finalSignal:signal.finalSignal,confidence:signal.confidence,regime:signal.marketRegime},paperOnly:true});audit('paper_signal_cycle',{result:'PASS',signal:signal.finalSignal,confidence:signal.confidence,regime:signal.marketRegime,executionAllowed:false,reason:'REAL_EXECUTION_DISABLED',ordersSent:0});}
async function start(){if(LIVE_ENABLED)throw new Error('AUREVIX_LIVE_TRADING_MUST_REMAIN_DISABLED');if(!databaseConfigured())throw new Error('AUTHORITATIVE_DATABASE_URL_NOT_CONFIGURED');await initDurableState();lease=await acquireLease({ownerId:runtimeId,ttlMs:90000});if(!lease.acquired)throw new Error('EXECUTION_AUTHORITY_NOT_ACQUIRED');await fencedWrite({key:'runtime',ownerId:runtimeId,fence:lease.fence,payload:{runtimeId,state:'PAPER_RUNTIME',liveEnabled:false,ordersSent:0,positionsModified:0}});audit('durable_authority_acquired',{fence:lease.fence,expiresAt:lease.expiresAt});setInterval(async()=>{try{const r=await renewLease({ownerId:runtimeId,fence:lease.fence,ttlMs:90000});if(!r.renewed){lease=null;lastError='AUTHORITY_LOST_NEW_EXECUTION_BLOCK';audit('execution_authority_lost',{reason:lastError});return;}lease={...lease,...r};await fencedWrite({key:'heartbeat',ownerId:runtimeId,fence:lease.fence,payload:{runtimeId,at:new Date().toISOString(),leaseFence:lease.fence,schedulerHealthy:true,liveEnabled:false}});}catch(e){lease=null;lastError=e.message;audit('lease_renewal_failed',{reason:lastError});}},15000);await cycle();setInterval(()=>cycle().catch(e=>{lastError=e.message;audit('cycle_error',{error:lastError})}),30000);}
const server=http.createServer((req,res)=>{if(req.url==='/health'||req.url==='/'){const body={service:'aurevix-elite-durable-runtime',runtimeId,readiness:gate()?'READY_HEALTHY':'BLOCKED',liveEnabled:false,ordersSent:0,positionsModified:0,realSlTpModifications:0,canaryStarted:false,preflightDone,lease:lease?{fence:lease.fence,expiresAt:lease.expiresAt}:null,lastCycle,lastReadOnly,lastError,signalCycles:signals};res.writeHead(gate()?200:503,{'content-type':'application/json'});res.end(JSON.stringify(body));return;}res.writeHead(404);res.end('not found');});
server.listen(PORT,()=>{audit('http_ready',{port:PORT});if(process.env.AUREVIX_PREFLIGHT_ONLY!=='1'){const child=spawn(process.execPath,['completion-preflight.mjs'],{env:{...process.env,AUREVIX_PREFLIGHT_ONLY:'1'},stdio:'inherit'});audit('completion_preflight_spawned',{pid:child.pid});child.on('exit',code=>{audit('completion_preflight_exit',{code});if(code===0){preflightDone=true;start().catch(e=>{lastError=e.message;audit('startup_blocked',{reason:lastError});process.exitCode=1;});}else{lastError='COMPLETION_PREFLIGHT_FAILED';audit('startup_blocked',{reason:lastError});}});}});
